apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kfserving-system
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- configmap.yaml
- secret.yaml
- service.yaml
- statefulset.yaml
- issuer.yaml
- webhook.yaml
commonLabels:
  kustomize.component: kfserving
configMapGenerator:
- name: kfserving-parameters
  env: params.env
vars:
- name: registry
  objref:
    kind: ConfigMap
    name: kfserving-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.registry
configurations:
- params.yaml
images:
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: gcr.io/kubebuilder/kube-rbac-proxy
  newTag: v0.4.0
- name: $(registry)/kfserving-controller
  newName: $(registry)/kfserving-controller
  newTag: v0.3.0
