apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- metadata-db-deployment.yaml
- metadata-deployment.yaml
- metadata-envoy-deployment.yaml
- metadata-ui-deployment.yaml
