apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- minio-artifact-secret.yaml
- workflow-controller-configmap.yaml
- workflow-controller-deployment.yaml
- workflow-controller-role.yaml
- workflow-controller-rolebinding.yaml
- workflow-controller-sa.yaml
  
# Used by Kustomize
configMapGenerator:
  - name: pipeline-install-config
    env: params.env

vars:
  - name: APP_NAME
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.appName
  - name: APP_VERSION
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.appVersion
  - name: IMAGE_PREFIX
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.imagePrefix
  - name: IMAGE_TAG
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.imageTag
  - name: DBSERVICE_HOST
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.dbHost
  - name: DBSERVICE_PORT
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.dbPort
  - name: DBNAME_MLMD
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.mlmdDb
  - name: DBNAME_CACHE
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.cacheDb
  - name: DBNAME_PIPELINE
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.pipelineDb
  - name: BUCKET_NAME
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.bucketName

configurations:
  - params.yaml
