apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  application-crd-id: kubeflow-pipelines

namespace: kubeflow

resources:
- minio-deployment.yaml
- minio-pvc.yaml
- minio-service.yaml
- minio-virtualservice.yaml
