apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  application-crd-id: kubeflow-pipelines

namespace: kubeflow

resources:
- mysql-deployment.yaml
- mysql-pv-claim.yaml
- mysql-service.yaml
