# Allow Kustomize var to replace following fields.
varReference:
- path: metadata/name
  kind: Application
- path: spec/descriptor/version
  kind: Application
- path: spec/template/spec/containers/image
  kind: Deployment
