apiVersion: apps/v1
kind: Deployment
metadata:
  name: activator
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/nodetype
                operator: In
                values:
                - kubeflow

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-hpa
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/nodetype
                operator: In
                values:
                - kubeflow

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/nodetype
                operator: In
                values:
                - kubeflow

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: networking-istio
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/nodetype
                operator: In
                values:
                - kubeflow

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/nodetype
                operator: In
                values:
                - kubeflow

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/nodetype
                operator: In
                values:
                - kubeflow
