apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- scheduled-workflow-crd.yaml
- viewer-crd.yaml
- cache-deployer-clusterrole.yaml
- cache-deployer-clusterrolebinding.yaml
- workflow-crd.yaml
