apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ml-pipeline-apiserver-deployment.yaml
- ml-pipeline-apiserver-role.yaml
- ml-pipeline-apiserver-rolebinding.yaml
- ml-pipeline-apiserver-sa.yaml
- ml-pipeline-apiserver-service.yaml
- ml-pipeline-persistenceagent-deployment.yaml
- ml-pipeline-persistenceagent-role.yaml
- ml-pipeline-persistenceagent-rolebinding.yaml
- ml-pipeline-persistenceagent-sa.yaml
- ml-pipeline-scheduledworkflow-deployment.yaml
- ml-pipeline-scheduledworkflow-role.yaml
- ml-pipeline-scheduledworkflow-rolebinding.yaml
- ml-pipeline-scheduledworkflow-sa.yaml
- ml-pipeline-ui-deployment.yaml
- ml-pipeline-ui-role.yaml
- ml-pipeline-ui-rolebinding.yaml
- ml-pipeline-ui-sa.yaml
- ml-pipeline-ui-service.yaml
- ml-pipeline-viewer-crd-role.yaml
- ml-pipeline-viewer-crd-rolebinding.yaml
- ml-pipeline-viewer-crd-deployment.yaml
- ml-pipeline-viewer-crd-sa.yaml
- ml-pipeline-visualization-deployment.yaml
- ml-pipeline-visualization-sa.yaml
- ml-pipeline-visualization-service.yaml
- pipeline-runner-role.yaml
- pipeline-runner-rolebinding.yaml
- pipeline-runner-sa.yaml
- container-builder-sa.yaml
- virtualservice.yaml

# Used by Kustomize
configMapGenerator:
  - name: pipeline-install-config
    env: params.env

secretGenerator:
  - name: mysql-secret
    env: params-db-secret.env

vars:
  - name: APP_NAME
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.appName
  - name: APP_VERSION
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.appVersion
  - name: IMAGE_PREFIX
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.imagePrefix
  - name: IMAGE_TAG
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.imageTag
  - name: DBSERVICE_HOST
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.dbHost
  - name: DBSERVICE_PORT
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.dbPort
  - name: DBNAME_MLMD
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.mlmdDb
  - name: DBNAME_CACHE
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.cacheDb
  - name: DBNAME_PIPELINE
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.pipelineDb
  - name: BUCKET_NAME
    objref:
      kind: ConfigMap
      name: pipeline-install-config
      apiVersion: v1
    fieldref:
      fieldpath: data.bucketName

configurations:
  - params.yaml
