apiVersion: batch/v1
kind: Job
metadata:
  name: crd-cleanup
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/nodetype
                operator: In
                values:
                - kubeflow
